core/urls.py
from django.urls import path
from .views import *

app_name = 'core'

urlpatterns = [
    path('carousel', carousel, name='carousel'),
    path('', home, name='home'),
    path('filter/<str:ctg>/<str:ctg2>', home1, name='home1'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', order_summary, name='order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    # path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('successPayment/', SuccesPayment, name='success'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),
]

core/models.py
from django.db.models.signals import post_save
from django.conf import settings
from django.db import models
from django.shortcuts import reverse
from django_countries.fields import CountryField


ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)


class SubCategory(models.Model):
    title = models.CharField(max_length=16)

    def __str__(self):
        return self.title


class Category(models.Model):
    title = models.CharField(max_length=30)
    subcategory = models.ForeignKey(SubCategory, on_delete=True, default=None)

    def __str__(self):
        return self.title + " " + self.subcategory.title


class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)
    image = models.ImageField(default=None)

    def __str__(self):
        return self.user.username


class Brand(models.Model):
    title = models.CharField(max_length=15)
    category = models.ForeignKey(Category, null=True, on_delete=True, default=None)

    def __str__(self):
        return self.title


class Item(models.Model):
    volume = models.IntegerField(default=100)
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=True, default=None)
    slug = models.SlugField()
    brand = models.ForeignKey(Brand, null=True, on_delete=True)
    description = models.TextField(default="NONE")
    description1 = models.TextField(default="NONE")
    description2 = models.TextField(default="NONE")
    image = models.ImageField()

    def __str__(self):
        return self.title

    def get_price(self):
        return int(self.price)

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug': self.slug
        })


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, null=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    shipping_address = models.ForeignKey(
        'Address', related_name='shipping_address', on_delete=models.SET_NULL, null=True)
    payment = models.BooleanField(default=False)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, null=True, default=None)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)
    v_obrabotke = models.BooleanField(default=False)
    def __str__(self):
        if self.payment == True:
            if self.v_obrabotke == True:
                return "Номер заказа: " + str(self.id) + " Оплачено. В обработке"
            return "Номер заказа: " + str(self.id) + " Оплачено. Не обработано"
        return self.user.username + ". Номер заказа: " + str(self.id) + " Не оплачено"


    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100, null=True)
    apartment_address = models.CharField(max_length=100, null=True)
    country = CountryField(multiple=False,null=True)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    phone_number = models.CharField(max_length=50)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'


class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.pk}"


def userprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        userprofile = UserProfile.objects.create(user=instance)


post_save.connect(userprofile_receiver, sender=settings.AUTH_USER_MODEL)

templates/base.html
{% load static %}
{% csrf_token %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cormorant+SC:wght@300&family=Domine:wght@500&family=Lato:wght@300&display=swap" rel="stylesheet">

  <style type="text/css">
      *{
        font-weight: bold;
        font-family: 'Cormorant SC', serif;
    }
    html,
    body,
    header{
        background: white;
      height: 60vh;
        margin: 0;
        padding: 0;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 0px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>
<body>
     {% include "navbar.html" %}
    {% block content %}
    {% endblock content %}

    {% block extra_body %}
    {% endblock %}

    {% include "footer.html" %}
    {% include "scripts.html" %}

    {% block extra_scripts %}
    {% endblock extra_scripts %}
</body>
</html>

templates/navbar.html
{% load cart_template_tags %}
{% load static %}

    <!-- Topbar Start -->
    <div class="container-fluid">
        <div class="row bg-secondary py-1 px-xl-5">
            <div class="col-lg-6 d-none d-lg-block">
                <div class="d-inline-flex align-items-center h-100">
                    <a class="text-body mr-3" href="">Контакты</a>
                    <a class="text-body mr-3" href="">Помощь</a>
                    <a class="text-body mr-3" href="">FAQs</a>
                </div>
            </div>
            <div class="col-lg-6 text-center text-lg-right">
                <div class="d-inline-flex align-items-center">
                    <div class="btn-group">
                        {% if not request.user.is_authenticated %}
                        <button type="button" class="btn btn-sm btn-light dropdown-toggle" data-toggle="dropdown">Мой Аккаунт</button>
                        <div class="dropdown-menu dropdown-menu-right">
                            <a href="{% url 'account_login' %}"  class="dropdown-item">Войти</a>
                            <a href="{% url 'account_signup' %}" class="dropdown-item">Зарегистрироваться</a>
                        </div>
                        {% else %}
                            <a href="{% url 'account_logout' %}">Выход с аккаунта</a>
                        {% endif %}
                    </div>
                </div>
                <div class="d-inline-flex align-items-center d-block d-lg-none">
                    <a href="{% url 'core:order-summary' %}" class="btn px-0 ml-2">
                        <i class="fas fa-heart text-dark"></i>
                        <span class="badge text-dark border border-dark rounded-circle" style="padding-bottom: 2px;">0</span>
                    </a>
                    <a href="{% url 'core:order-summary' %}" class="btn px-0 ml-2">
                        <i class="fas fa-shopping-cart text-dark"></i>
                        <span class="badge text-dark border border-dark rounded-circle" style="padding-bottom: 2px;">0</span>
                    </a>
                </div>
            </div>
        </div>
        <div class="row align-items-center bg-light py-3 px-xl-5 d-none d-lg-flex">
            <div class="col-lg-4">
                <a href="{% url 'core:home' %}" class="text-decoration-none">
                    <span class="h1 text-uppercase text-primary bg-dark px-2">YBeauty</span>
                    <span class="h1 text-uppercase text-dark bg-primary px-2 ml-n1">Shop</span>
                </a>
            </div>
            <div class="col-lg-4 col-6 text-left">
                <form action="">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search for products">
                        <div class="input-group-append">
                            <span class="input-group-text bg-transparent text-primary">
                                <i class="fa fa-search"></i>
                            </span>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-lg-4 col-6 text-right">
                <p class="m-0">Служба поддержки</p>
                <h5 class="m-0">+012 345 6789</h5>
            </div>
        </div>
    </div>
    <!-- Topbar End -->


    <!-- Navbar Start -->
    <div class="container-fluid bg-dark mb-30" style="margin-bottom: 0px; padding-bottom: 0px">
        <div class="row px-xl-5">
            <div class="col-lg-3 d-none d-lg-block">
                <a class="btn d-flex align-items-center justify-content-between bg-primary w-100" data-toggle="collapse" href="#navbar-vertical" style="height: 65px; padding: 0 30px;">
                    <h6 class="text-dark m-0"><i class="fa fa-bars mr-2"></i>Категории</h6>
                    <i class="fa fa-angle-down text-dark"></i>
                </a>
                <nav class="collapse position-absolute navbar navbar-vertical navbar-light align-items-start p-0 bg-light" id="navbar-vertical" style="width: calc(100% - 30px); z-index: 999;">
                    <div class="navbar-nav w-100">
                         <div class="nav-item dropdown dropright">
                            <a href="" class="nav-link dropdown-toggle" data-toggle="dropdown">Парфюмы <i class="fa fa-angle-right float-right mt-1"></i></a>
                            <div class="dropdown-menu position-absolute rounded-0 border-0 m-0">
                                <a href="{% url 'core:home1' ctg='Парфюмы' ctg2='Мужской' %}" class="dropdown-item">Мужские Парфюмы</a>
                                <a href="{% url 'core:home1' ctg='Парфюмы' ctg2='Женский' %}" class="dropdown-item">Женские Парфюмы</a>
                            </div>
                        </div>
                        <div class="nav-item dropdown dropright">
                            <a href="" class="nav-link dropdown-toggle" data-toggle="dropdown">Уход за Кожей <i class="fa fa-angle-right float-right mt-1"></i></a>
                            <div class="dropdown-menu position-absolute rounded-0 border-0 m-0">
                                <a href="{% url 'core:home1' 'Уход за Кожей' 'Лицо' %}" class="dropdown-item">Для Лица</a>
                                <a href="{% url 'core:home1' 'Уход за Кожей' 'Тело' %}" class="dropdown-item">Для Тела</a>
                                <a href="{% url 'core:home1' 'Уход за Кожей' 'Тело' %}" class="dropdown-item">Для Бороды</a>
                            </div>
                        </div>
                        <a href="{% url 'core:home1' 'Декоративная Косметика' 'None'%}" class="nav-item nav-link">Декоративная Косметика</a>
                        <div class="nav-item dropdown dropright">
                            <a href="" class="nav-link dropdown-toggle" data-toggle="dropdown">Подарочный Наборы <i class="fa fa-angle-right float-right mt-1"></i></a>
                            <div class="dropdown-menu position-absolute rounded-0 border-0 m-0">
                                <a href="{% url 'core:home1' 'Подарочный Наборы' 'Мужской' %}" class="dropdown-item">Мужские</a>
                                <a href="{% url 'core:home1' 'Подарочный Наборы' 'Женский'%}" class="dropdown-item">Женские</a>
                            </div>
                        </div>
                        <div class="nav-item dropdown dropright">
                            <a href="" class="nav-link dropdown-toggle" data-toggle="dropdown">Для Дома <i class="fa fa-angle-right float-right mt-1"></i></a>
                            <div class="dropdown-menu position-absolute rounded-0 border-0 m-0">
                                <a href="{% url 'core:home1' 'Для Дома' 'Диффузоры'%}" class="dropdown-item">Диффузоры</a>
                                <a href="{% url 'core:home1' 'Для Дома' 'Бахуры'%}" class="dropdown-item">Бахуры</a>
                                <a href="{% url 'core:home1' 'Для Дома' 'Ароматизаторы'%}" class="dropdown-item">Ароматизаторы</a>
                            </div>
                        </div>
                    </div>
                </nav>
            </div>
            <div class="col-lg-9">
                <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-3 py-lg-0 px-0">
                    <a href="{% url 'core:home' %}" class="text-decoration-none d-block d-lg-none">
                        <span class="h1 text-uppercase text-dark bg-light px-2">Ybeauty</span>
                        <span class="h1 text-uppercase text-light bg-primary px-2 ml-n1">Shop</span>
                    </a>
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">

                        <div class="nav-item dropdown dropdown">
                            <a href="" class="nav-link dropdown-toggle" data-toggle="dropdown">Парфюмы <i class="fa fa-angle-right float-right mt-1"></i></a>
                            <div class="dropdown-menu position-absolute rounded-0 border-0 m-0">
                                <a href="{% url 'core:home1' ctg='Парфюмы' ctg2='Мужской' %}" class="dropdown-item">Мужские Парфюмы</a>
                                <a href="{% url 'core:home1' ctg='Парфюмы' ctg2='Женский' %}" class="dropdown-item">Женские Парфюмы</a>
                            </div>
                        </div>
                        <div class="nav-item dropdown dropdown">
                            <a href="" class="nav-link dropdown-toggle" data-toggle="dropdown">Уход за Кожей <i class="fa fa-angle-right float-right mt-1"></i></a>
                            <div class="dropdown-menu position-absolute rounded-0 border-0 m-0">
                                <a href="{% url 'core:home1' 'Уход за Кожей' 'Лицо' %}" class="dropdown-item">Для Лица</a>
                                <a href="{% url 'core:home1' 'Уход за Кожей' 'Тело' %}" class="dropdown-item">Для Тела</a>
                                <a href="{% url 'core:home1' 'Уход за Кожей' 'Тело' %}" class="dropdown-item">Для Бороды</a>
                            </div>
                        </div>
                        <a href="{% url 'core:home1' 'Декоративная Косметика' 'None'%}" class="nav-item nav-link">Декоративная Косметика</a>
                        <div class="nav-item dropdown dropdown">
                            <a href="" class="nav-link dropdown-toggle" data-toggle="dropdown">Подарочный Наборы <i class="fa fa-angle-right float-right mt-1"></i></a>
                            <div class="dropdown-menu position-absolute rounded-0 border-0 m-0">
                                <a href="{% url 'core:home1' 'Подарочный Наборы' 'Мужской' %}" class="dropdown-item">Мужские</a>
                                <a href="{% url 'core:home1' 'Подарочный Наборы' 'Женский'%}" class="dropdown-item">Женские</a>
                            </div>
                        </div>
                        <div class="nav-item dropdown dropdown">
                            <a href="" class="nav-link dropdown-toggle" data-toggle="dropdown">Для Дома <i class="fa fa-angle-right float-right mt-1"></i></a>
                            <div class="dropdown-menu position-absolute rounded-0 border-0 m-0">
                                <a href="{% url 'core:home1' 'Для Дома' 'Диффузоры'%}" class="dropdown-item">Диффузоры</a>
                                <a href="{% url 'core:home1' 'Для Дома' 'Бахуры'%}" class="dropdown-item">Бахуры</a>
                                <a href="{% url 'core:home1' 'Для Дома' 'Ароматизаторы'%}" class="dropdown-item">Ароматизаторы</a>
                            </div>
                        </div>

                    </div>
                </nav>
            </div>
        </div>
    </div>
    <!-- Navbar End -->

templates/order_snippet.html
<div class="col-md-12 mb-4">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
    <span class="text-muted">Ваш заказ</span>
    <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
    </h4>
    <ul class="list-group mb-3 z-depth-1">
    {% for order_item in order.items.all %}
    <li class="list-group-item d-flex justify-content-between lh-condensed">
        <div>
        <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.title}}</h6>
        <small class="text-muted">{{ order_item.item.description}}</small>
        </div>
        <span class="text-muted">₸{{ order_item.get_final_price }}</span>
    </li>
    {% endfor %}
    {% if order.coupon %}
    <li class="list-group-item d-flex justify-content-between bg-light">
        <div class="text-success">
        <h6 class="my-0">Promo code</h6>
        <small>{{ order.coupon.code }}</small>
        </div>
        <span class="text-success">-₸{{ order.coupon.amount }}</span>
    </li>
    {% endif %}
    <li class="list-group-item d-flex justify-content-between">
        <span>Сумма к оплате</span>
        <strong>₸{{ order.get_total }}</strong>
    </li>
    </ul>

    {% if DISPLAY_COUPON_FORM %}
    <form class="card p-2" action="{% url 'core:add-coupon' %}" method="POST">
        {% csrf_token %}
        <div class="input-group">
            {{ couponform.code }}
            <div class="input-group-append">
            <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Применить</button>
            </div>
        </div>
    </form>
    {% endif %}

</div>

templates/order_summary.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="utf-8">
    <title>Ybeauty.kz</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/animate/animate.min.css'%}" rel="stylesheet">
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static  'css/style4.css'%}" rel="stylesheet">
</head>

<body>
    {% include "navbar.html" %}
    <div class="container">

    <div class="table-responsive text-nowrap">
    <h2 style="margin-top: 30px">Ваш заказ</h2>
    <table class="table">
        <thead>
        <tr>
            <th scope="col"></th>
            <th scope="col">Название</th>
            <th scope="col">Цена</th>
            <th scope="col">Количество</th>
            <th scope="col">Сумма</th>
        </tr>
        </thead>
        <body>
        {% for object in objects %}
        {% for order_item in object.items.all %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ order_item.item.title }}</td>
            <td>{{ order_item.item.price }}</td>
            <td>
                <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i class="fas fa-minus mr-2"></i></a>
                {{ order_item.quantity }}
                <a href="{% url 'core:add-to-cart' order_item.item.slug %}"><i class="fas fa-plus ml-2"></i></a>
            </td>
            <td>
            {% if order_item.item.discount_price %}
                ₸{{ order_item.get_total_discount_item_price }}
                <span class="badge badge-primary">Saving ₸{{ order_item.get_amount_saved }}</span>
            {% else %}
                ₸{{ order_item.get_total_item_price }}
            {% endif %}
            <a style='color: red;' href="{% url 'core:remove-from-cart' order_item.item.slug %}">
                <i class="fas fa-trash float-right"></i>
            </a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan='5'>Your cart is empty</td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-primary float-right' onclick="" href='/'>Continue shopping</a>
            </td>
        </tr>
        {% endfor %}
        {% if object.coupon %}
        <tr>
            <td colspan="4"><b>Coupon</b></td>
            <td><b>-₸{{ object.coupon.amount }}</b></td>
        </tr>
        {% endif %}
        {% if object.get_total %}
        <tr>
            <td colspan="4"><b>К оплате :</b></td>
            <td><b>₸{{ object.get_total }}</b></td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-warning float-right ml-2' href='/checkout/'>Перейти к оплате</a>
            <a class='btn btn-primary float-right' href='/'>Продолжить покупки</a>
            </td>
        </tr>
        {% endif %}
        {% endfor %}
        </body>
    </table>

    </div>

    </div>
</body>

templates/product.html
{% extends "base.html" %}
{% block content %}
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="{{ object.image.url }}" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{ object.get_category_display }}</span>
              </a>
            </div>

            <p class="lead">
              {% if object.discount_price %}
              <span class="mr-1">
                <del>₸{{ object.price }}</del>
              </span>
              <span>₸{{ object.discount_price }}</span>
              {% else %}
              <span>{{ object.price }}₸</span>
              {% endif %}
            </p>

            <p class="lead font-weight-bold">Описание</p>

            <p>{{ object.description }}</p>

            {% comment %} <form class="d-flex justify-content-left">
              <!-- Default input -->
              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              <button class="btn btn-primary btn-md my-0 p" type="submit">
                Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>

            </form> {% endcomment %}
            <a href="{{ object.get_add_to_cart_url }}"   class="btn btn-primary btn-md my-0 p" style="color: black">
              Добавить в корзину
              <i class="fas fa-shopping-cart ml-1"></i>
            </a>
            <a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p">
              Удалить с корзины
            </a>

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>
      <!--Grid row-->

    </div>
  </main>

{% endblock content %}

templates/request_refund.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <main>
    <div class="container">

    <h2>Request Refund</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class='btn btn-primary'>Submit</button>
    </form>

    </div>
  </main>

{% endblock content %}

templates/scripts.html
{% load static %}
<script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<!-- Initializations -->
<script type="text/javascript">
  // Animations initialization
  new WOW().init();

</script>